#!/usr/bin/env python
from __future__ import print_function
import sys
import hermes
if len(sys.argv)<3:
    print("Useage: allarms [data directory] [reduction directory]")
hermes.go_all(sys.argv[1], sys.argv[2], "./cal/")