#!/usr/bin/env python
from __future__ import print_function
import sys
import hermes
if len(sys.argv)<4:
    print("Useage: listreduce [data directory] [reduction directory] [list file] [append_string]")
if len(sys.argv)>4:
    append_string=sys.argv[4]
else:
    append_string=''
with open(sys.argv[3],'r') as dir_list:
    for dir_name in dir_list.readlines():
        dir_name = dir_name[:-1] #Trim newline
        hermes.go_all(sys.argv[1]+'/'+dir_name + '/' + append_string, sys.argv[2]+'/'+dir_name, './cal')
