#!/usr/bin/env python
from __future__ import print_function
import sys
import hermes
import time
repeat_analysis_time = 20
if len(sys.argv)<3:
    print("Useage: allarms [data directory] [reduction directory]")
    sys.exit()
while True:
    print("**** Starting reduction ****")
    hermes.go_all(sys.argv[1], sys.argv[2], "./cal/", skip_done=True)
    print("**** Pausing (repeat time {0:d} seconds) ****".format(repeat_analysis_time))
    time.sleep(repeat_analysis_time)
